In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df =pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
gc=pd.read_csv('gender_submission.csv')
print(df.isnull().sum()) # to see total no of 0s in a column


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
df.drop('Name',axis=1,inplace=True)
df.drop('Ticket',axis=1,inplace=True)
df.drop('Cabin',axis=1,inplace=True)
df.drop('PassengerId',axis=1,inplace=True)
df.dropna(inplace = True) #to drop all the rows with nan val
print(df)

test.drop('Name',axis=1,inplace=True)
test.drop('Ticket',axis=1,inplace=True)
test.drop('Cabin',axis=1,inplace=True)
test.drop('PassengerId',axis=1,inplace=True)
print(test)


     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
885         0       3  female  39.0      0      5  29.1250        Q
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[712 rows x 8 columns]
     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0   

In [ ]:
print(test.isnull().sum())
test.info()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [ ]:
gc.drop('PassengerId',axis=1,inplace=True)
print(gc)

     Survived
0           0
1           1
2           0
3           0
4           1
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]


In [ ]:
X=df.drop('Survived',axis=1)
y=df['Survived']
print(X)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
885       3  female  39.0      0      5  29.1250        Q
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[712 rows x 7 columns]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df[['Age']] = imputer.fit_transform(df[['Age']])

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
test[['Age']] = imputer.fit_transform(test[['Age']])
test[['Fare']] = imputer.fit_transform(test[['Fare']])


In [ ]:
print(test.isnull().sum())
print(df.isnull().sum()) # to see total no of 0s in a column'

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64
Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64


In [ ]:
#print(df.isnull().sum()) # to see total no of 0s in a column
print(X)
print(test)


     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
885       3  female  39.0      0      5  29.1250        Q
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[712 rows x 7 columns]
     Pclass     Sex       Age  SibSp  Parch      Fare Embarked
0         3    male  34.50000      0      0    7.8292        Q
1         3  female  47.00000      1      0    7.0000        S
2         2    male  62.00000      0      0    9.6875        Q
3         3    male  27.0000

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['Sex']= le.fit_transform(X['Sex'])
unique_species = X['Sex'].unique()
print(X)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
test['Sex']= le.fit_transform(test['Sex'])
unique_species = test['Sex'].unique()
print(test)

     Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         3    1  22.0      1      0   7.2500        S
1         1    0  38.0      1      0  71.2833        C
2         3    0  26.0      0      0   7.9250        S
3         1    0  35.0      1      0  53.1000        S
4         3    1  35.0      0      0   8.0500        S
..      ...  ...   ...    ...    ...      ...      ...
885       3    0  39.0      0      5  29.1250        Q
886       2    1  27.0      0      0  13.0000        S
887       1    0  19.0      0      0  30.0000        S
889       1    1  26.0      0      0  30.0000        C
890       3    1  32.0      0      0   7.7500        Q

[712 rows x 7 columns]
     Pclass  Sex       Age  SibSp  Parch      Fare Embarked
0         3    1  34.50000      0      0    7.8292        Q
1         3    0  47.00000      1      0    7.0000        S
2         2    1  62.00000      0      0    9.6875        Q
3         3    1  27.00000      0      0    8.6625        S
4         3    0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X=ct.fit_transform(X)
print(X)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
test=ct.fit_transform(test)
print(test)

[[ 0.      0.      1.     ...  1.      0.      7.25  ]
 [ 1.      0.      0.     ...  1.      0.     71.2833]
 [ 0.      0.      1.     ...  0.      0.      7.925 ]
 ...
 [ 0.      0.      1.     ...  0.      0.     30.    ]
 [ 1.      0.      0.     ...  0.      0.     30.    ]
 [ 0.      1.      0.     ...  0.      0.      7.75  ]]
[[ 0.      1.      0.     ...  0.      0.      7.8292]
 [ 0.      0.      1.     ...  1.      0.      7.    ]
 [ 0.      1.      0.     ...  0.      0.      9.6875]
 ...
 [ 0.      0.      1.     ...  0.      0.      7.25  ]
 [ 0.      0.      1.     ...  0.      0.      8.05  ]
 [ 1.      0.      0.     ...  1.      1.     22.3583]]


In [ ]:
first_n_rows = X[:15, :]
print(first_n_rows)

first_n_rows = test[:15, :]
print(first_n_rows)

[[ 0.      0.      1.      3.      1.     22.      1.      0.      7.25  ]
 [ 1.      0.      0.      1.      0.     38.      1.      0.     71.2833]
 [ 0.      0.      1.      3.      0.     26.      0.      0.      7.925 ]
 [ 0.      0.      1.      1.      0.     35.      1.      0.     53.1   ]
 [ 0.      0.      1.      3.      1.     35.      0.      0.      8.05  ]
 [ 0.      0.      1.      1.      1.     54.      0.      0.     51.8625]
 [ 0.      0.      1.      3.      1.      2.      3.      1.     21.075 ]
 [ 0.      0.      1.      3.      0.     27.      0.      2.     11.1333]
 [ 1.      0.      0.      2.      0.     14.      1.      0.     30.0708]
 [ 0.      0.      1.      3.      0.      4.      1.      1.     16.7   ]
 [ 0.      0.      1.      1.      0.     58.      0.      0.     26.55  ]
 [ 0.      0.      1.      3.      1.     20.      0.      0.      8.05  ]
 [ 0.      0.      1.      3.      1.     39.      1.      5.     31.275 ]
 [ 0.      0.      1.    

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X,y)     #only X and y if training on whole dataset

KNeighborsClassifier()

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X,y)   #only X and y if training on whole dataset

SVC(random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X, y)    #only X and y if training on whole dataset
#Maximum

GaussianNB()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X,y)    #only X and y if training on whole dataset

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X,y)   #only X and y if training on whole dataset

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=15,criterion='entropy',random_state=0)
classifier.fit(X,y)  #only X and y if training on whole dataset

RandomForestClassifier(criterion='entropy', n_estimators=15, random_state=0)

**Prediction&Result**

In [ ]:
y_pred=classifier.predict(test)  #y_pred shape is determined by the number of rows in the test dataset
y_pred.shape


(418,)

In [ ]:
gc.shape

(418, 1)

In [ ]:
y_pred = y_pred.reshape(len(y_pred), 1)
gc = gc.values.reshape(len(gc), 1) # Convert y_test to a NumPy array using .values
#gc = gc.reshape(len(gc), 1)

# Extract the 'Survived' column from gender_submission and reshape it
#gc= gc['Survived'].values.reshape(len(gc),axis= 1)

# Concatenating the reshaped arrays along axis 1
result = np.concatenate((y_pred,gc), axis=1)
#print(result)

In [ ]:
y_pred.shape

(418, 1)

In [ ]:
gc.shape

(418, 1)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred,gc)
print(cm)
accuracy_score(y_pred,gc)

[[236  44]
 [ 30 108]]


0.8229665071770335